**Задача 1**

Даны значения величины заработной платы заемщиков банка ($zp$) и значения их
поведенческого кредитного скоринга ($ks$):

$zp = [35, 45, 190, 200, 40, 70, 54, 150, 120, 110]$,

$ks = [401, 574, 874, 919, 459, 739, 653, 902, 746, 832]$.

Найдите ковариацию этих двух величин с помощью элементарных действий, а затем с
помощью функции *cov* из *numpy*.
Полученные значения должны быть равны.
Найдите коэффициент *корреляции Пирсона* с помощью ковариации и
среднеквадратичных отклонений двух признаков,
а затем с использованием функций из библиотек *numpy* и *pandas*.

$cov_{XY}=M(XY)-M(X)*M(Y)$

In [6]:
import numpy as np
import pandas as pd
from scipy import stats
from matplotlib import pyplot as plt

In [7]:
zp = [35, 45, 190, 200, 40, 70, 54, 150, 120, 110]
ks = [401, 574, 874, 919, 459, 739, 653, 902, 746, 832]

In [9]:
XY = 0
X = 0
Y = 0
n = len(zp)
for i in range(0, n):
    XY = XY + zp[i] * ks[i]
    X = X + zp[i]
    Y = Y + ks[i]

X_avg = X/n
Y_avg = Y/n
cov = XY/n - X_avg * Y_avg
cov

9157.839999999997

In [10]:
np.cov(zp, ks, ddof=0)

array([[ 3494.64,  9157.84],
       [ 9157.84, 30468.89]])

In [12]:
sum1 = 0
for i in range(0, n):
    sum1 = sum1 + (zp[i] - X_avg) * (ks[i] - Y_avg)

cov_n = 1 / (n - 1) * sum1
cov_n

10175.377777777776

In [13]:
np.cov(zp, ks, ddof=1)

array([[ 3882.93333333, 10175.37777778],
       [10175.37777778, 33854.32222222]])

$\sigma^2=\frac{1}{m}\displaystyle\sum_{i=1}^m(x_i-\bar{x})^2$

In [14]:
sum_X = 0
sum_Y = 0
for i in range(0, n):
    sum_X = sum_X + (zp[i] - X_avg)**2
    sum_Y = sum_Y + (ks[i] - Y_avg)**2

Dx = 1/(n)*sum_X
Dy = 1/(n)*sum_Y
scale_X = Dx**0.5
scale_Y = Dy**0.5
print(Dx, scale_X)
print(Dy, scale_Y)

3494.6400000000003 59.115480206118605
30468.89000000001 174.55340157098058


In [ ]:
r = cov/(scale_X * scale_Y)
r

In [15]:
np.corrcoef(zp, ks)

array([[1.        , 0.88749009],
       [0.88749009, 1.        ]])